### ISSUE TITLE
Add offset to needle tip

### ISSUE THREAD

**Issue by satnamsvirdi** [mattrothenberg/use-gauge#12]
I'd like to request you a feature to add offset to needle.

## Background
I'm using a gauge like component in one of our app and your hook was a perfect choice for that use case. But our designer suggested to add some spacing between the needle tip and upon checking the readme and the code I've found that there were no options to do this. 

## Solution
As as solution, I've added a PR to add the missing functionality, so the others can benefit from it as well. You can take a look at the open PR [here](https://github.com/mattrothenberg/use-gauge/pull/11). 

Feel free to share your thoughts/suggestions, if any. 

Lastly, thank you for this amazing hook!

**Comment by mattrothenberg** [comment]
Thanks!
