### ISSUE TITLE
Issue with certain numbers

### ISSUE THREAD

**Issue by raRaRa** [mattrothenberg/use-gauge#13]
Hey there. First of all, thank you for an excellent gauge hook for React, really appreciate it!

I've run into one issue where I'm showing solar KP index on a gauge. I have values ranging from 0 to 9. When the value is 8, the needle doesn't seem to point at the correct value. 

<img width="1086" alt="image" src="https://github.com/mattrothenberg/use-gauge/assets/4303914/7aa6cc34-ea3d-46a9-9894-740a6af212b5">

Values such as 0, 5 and 9 seem to work fine.

Any clue what the issue could be? I've tried digging into the source code, removed all cases of `Math.floor` and `Math.round`, it looks a bit better but still obviously off.

Thank you.

**Comment by mattrothenberg** [comment]
Hello! That certainly looks like a bug. Are you able to share a
reproduction with me that I can debug further?

Matt Rothenberg
http://mattrothenberg.com
http://www.linkedin.com/in/mrothenberg

**Comment by raRaRa** [comment]
Ah, the issue seems to be that I set `9` to `numTicks`, instead of 10, since it's from 0 to 9. Setting it to 10 seems to fix it! Apologies!

**Comment by mattrothenberg** [comment]
Any ideas or recommendations on how to make that API clearer?

Matt Rothenberg
http://mattrothenberg.com
http://www.linkedin.com/in/mrothenberg

**Comment by raRaRa** [comment]
Good question. I'm wondering if `numTicks` beyond or below the range of the domain should not affect the needle like it did in my case.

But IMO the API feels really nice to work with. I'm just beginning to use it for a project and I'll make sure to leave some feedback if I get some ideas.

**Comment by mattrothenberg** [comment]
Yay! I’m happy to hear that. Open to any ideas :)

Matt Rothenberg
http://mattrothenberg.com
http://www.linkedin.com/in/mrothenberg

**Comment by raRaRa** [comment]
Super off-topic to this issue, but would it make more sense to use transform rotation on the needle, so that we can use CSS transition for it? That way I could make the needle move smoothly between values.

**Comment by mattrothenberg** [comment]
I think that could work? If you don't mind opening up a new issue I can take a look at that sometime soon. 🙏

**Comment by raRaRa** [comment]
Closing this issue to start a new one - this issue was just related to numTicks being off.
