### ISSUE TITLE
feature: Rotate the needle with CSS transform rotate to allow animation

### ISSUE THREAD

**Issue by raRaRa** [mattrothenberg/use-gauge#14]
I am working on a gauge that should move the needle smoothly. I was wondering if it would make more sense to use CSS transform to rotate the needle. That way one could enable transition on the transform for smooth rotation.

My current solution:

```
        <g
          id="needle"
          className={styles.needle}
          style={{
            transform: `rotate(${gauge.valueToAngle(value) - 90}deg)`,
          }}
        >
          <circle className={styles.needleBase} {...needle.base} r={12} />
          <circle className={styles.needleBase} {...needle.base} />
          <circle className={styles.needleTip} {...needle.tip} />
          <polyline className={styles.needlePoints} points={needle.points} />
          <circle className={styles.needleBase} {...needle.base} r={4} />
        </g>
```

CSS:

```
  .needle {
    transition: 0.2s ease-in-out;
  }
```

Then inside getNeedleProps I just hard-code the angle to 0.

For my use case this works beautifully.

**Comment by mattrothenberg** [comment]
I think this is a good idea, though I'm a little leery to make this a first-class feature of the library.

I like how, currently, `value` drives the presentation of the entire chart. I don't like how we'd have to resort to hard-coding certain values just to unlock a different state that permits CSS animations.

It's pretty trivial now to animate the chart using `requestAnimationFrame` and updating `value` according to whatever interval/easing you like.

https://github.com/mattrothenberg/use-gauge/assets/5148596/3e76ee20-67a3-43e6-b984-fd227e0a39d6

Any reason why CSS transitions feel like a better solution here?

**Comment by raRaRa** [comment]
Gotcha. CSS just feels more fluid, where you could introduce cubic-bezier and other cool effects without really affecting the value. I don't think the current API needs to change at all, since my method works great on top of the existing API by just adding a CSS transform to the needle.
