### ISSUE TITLE
Hard time using ticks and certain values for label

### ISSUE THREAD

**Issue by raRaRa** [mattrothenberg/use-gauge#15]
Hey there again!

I'm working on a gauge that displays solar wind from 200 to 1000.  I would love to be able to display 200, 300, 400, 500, 600, 700, 800, 900 and 1000 as ticks. But no matter what `numTicks` value I use, I always get result like this:

<img width="277" alt="image" src="https://github.com/mattrothenberg/use-gauge/assets/4303914/f54adc1c-3d9f-42cd-a867-02764851f25d">

Is there any good solution to this? Would I need to adjust the startAngle and endAngle?

**Comment by raRaRa** [comment]
Setting `numTicks` to 5 works, I guess because it can divide the numbers evenly, but that gives me too few ticks.

**Comment by mattrothenberg** [comment]
You'll likely need to change the implementation of this function.

https://github.com/mattrothenberg/use-gauge/blob/cf4c9012c11a0706debc30ca0c32190f16e34273/src/lib.ts#L5-L17

I'd welcome a PR that exposes a prop for a custom tick formatter function.

**Comment by raRaRa** [comment]
Hmm I managed to find a solution that works. So basically I put an offset of 2 to the startAngle and endAngle, so 90-2 and 270+2, that seems to hit the sweet spot

<img width="302" alt="image" src="https://github.com/mattrothenberg/use-gauge/assets/4303914/12a12993-c3dc-4d8a-9261-b07d21760fd3">

**Comment by raRaRa** [comment]
I don't think there's any "easy fix" to solve this. But perhaps you could instead show a demo on how to solve edge cases like these, e.g. with the offset trick. I'm closing this issue for now and will open another one if I figure something later.
