### ISSUE TITLE
Warning: A props object containing a "key" prop is being spread into JSX

### ISSUE THREAD

**Issue by CodeCup7** [mattrothenberg/use-gauge#16]
hi!
I have issue in NextJS 13
this line:
{...gauge.getTickProps({ angle, length: showText ? 12 : 6 })}
in arced.tsx

this error:
Warning: A props object containing a "key" prop is being spread into JSX:
  let props = {key: someKey, className: ..., strokeWidth: ..., x1: ..., x2: ..., y1: ..., y2: ...};
  <line {...props} />
React keys must be passed directly to JSX without using spread:
  let props = {className: ..., strokeWidth: ..., x1: ..., x2: ..., y1: ..., y2: ...};
  <line key={someKey} {...props} />

**Comment by mattrothenberg** [comment]
Can you please post a reproduction or link to a repository where this is happening?

**Comment by CodeCup7** [comment]
Thanks for your answer and for your interest in the problem. I created a new clean repository and implemeted the chart.

The issue have in console VScode. This is the link https://github.com/CodeCup7/chart-test

Thanks 

edit:
OK, I think the problem is using 'use client' but I don't know how to solve this problem :)

**Comment by mattrothenberg** [comment]
The `key` issue (which is Next.js specific) should be fixed in `0.7.0`.

**Comment by CodeCup7** [comment]
Super, because this chart is awesome :)
