### ISSUE TITLE
I want to add 4 dynamic values as ticks, low, high and medium value, but based on angle, and function angleToValue its not showing values How do I resolve this

### ISSUE THREAD

**Issue by kashkumar12** [mattrothenberg/use-gauge#7]
<g id="ticks">
            {gauge.ticks.map((angle) => {
              console.log(angle);
              const asValue = gauge.angleToValue(angle);
              console.log(asValue);
              const showText =
                asValue === 0 ||
                asValue === props.low||
                asValue === props.medium||
                asValue === props.high;
              return (
                <React.Fragment key={`tick-group-${angle}`}>
                  <line
                    className="stroke-gray-300"
                    strokeWidth={2}
                    {...gauge.getTickProps({
                      angle,
                      //length: 0,
                      length: showText ? 20 : 6,
                    })}
                  />
                  {showText && (
                    <>
                      <text
                        className="text-sm fill-gray-400 font-medium"
                        {...gauge.getLabelProps({ angle, offset: -38 })}
                      >
                        {asValue}
                      </text>
                    </>
                  )}
                </React.Fragment>
              );
            })}
          </g>

**Comment by mattrothenberg** [comment]
Hello! I'm not sure I understand what problem you're trying to solve. Can you please provide:
1. A visual example
2. A CodeSandbox with the code that's not working?

Thank you!

**Comment by kashkumar12** [comment]
Hi, Here is my code - [https://codesandbox.io/s/bold-curie-7k2t9y?file=/src/App.js](https://codesandbox.io/s/bold-curie-7k2t9y?file=/src/App.js) I want to show zero, low, high and medium in the form of  ticks (4 dynamic values ) and the ticks are dynamic value
![image](https://user-images.githubusercontent.com/30726728/160921607-f056ad5b-5c18-4b48-a761-e19662d1393c.png)
Thank you

**Comment by mattrothenberg** [comment]
@akshyaprakash This should give you an idea of how to solve this. Note that you can use the `angleToValue` helper function to convert a tick angle to a discrete numerical value.

https://codesandbox.io/s/infallible-leaf-hr2mq0?file=/src/App.tsx

**Comment by kashkumar12** [comment]
Hi @mattrothenberg, if you give like example low={160} the value is not displaying in the above example.
Its like whichever number I give it should display

Thank you

**Comment by mattrothenberg** [comment]
@akshyaprakash That's because the number of ticks you specify impacts the discrete numerical values returned by `angleToValue`. If you need finer grained customization here, you might need to do some arithmetic (to calculate whether a value is between X and Y).

I'm going to close this out, as it doesn't seem to be related to a bug/issue. It's a user-land concern.
