### ISSUE TITLE
How to add gradient to arch?

### ISSUE THREAD

**Issue by spacecat** [mattrothenberg/use-gauge#8]
My understanding is that this hook makes it so that you can design/customize your svg gauge however you want - not as user friendly but very flexible.

I checked all the code and examples but couldn't find an example where the arch would be of a gradient instead of a single color.

How would you go about doing this in the best possible way? I suck at SVG bug but instead of doing `fill="some color hex"` I would use some sort of gradient attribute, e.g. `gradient="fromvalue to value"`?

**Comment by mattrothenberg** [comment]
I recommend this article for understanding gradients in SVG land.

https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Gradients
